[Interface]
Address = 10.13.13.2
PrivateKey = cM0hQ3Y0aZ8lhikfCqrBywKZTKhSACLtCaf3ROjSXF8=
ListenPort = 51820
DNS = 1.1.1.1

[Peer]
PublicKey = uy83yOghb01BxdwsfCRdzmecYwSQtp6GAWYDc5I3BRA=
PresharedKey = yPfo7N5Lb3I83ddqGmVBFliswbDke8gsZepYOpk1b48=
Endpoint = 171.249.176.231:51820
AllowedIPs = 0.0.0.0/0, ::/0
